// We only store the base name! The Flutter parser will append 'assets/icons/' and '.svg'
export const AppIcons = {
  ALARM: "logo_alarm",
  BACK: "logo_back",
  CART: "logo_cart",
  DELETE: "logo_delete",
  EDIT: "logo_edit",
  EXIT: "logo_exit",
  FILTER: "logo_filter",
  GIFT: "logo_gift",
  HEART_EMPTY: "logo_heart_empty",
  HEART_FILLED: "logo_heart_filled",
  HOME: "logo_home",
  INFO: "logo_info",
  LOCK: "logo_lock",
  MESSAGE: "logo_message",
  NEXT: "logo_next",
  PERSON: "logo_person",
  PHONE: "logo_phone",
  SEARCH: "logo_search",
  SEND: "logo_send",
  SETTING: "logo_setting",
  STAR_FILLED: "logo_star_filled",
  STAR_EMPTY: "logo_star_empty",
  STORE: "logo_store",
};