// We only store the base name! The Flutter parser will append 'assets/icons/' and '.svg'
export const AppIcons = {
  PASSCODE:"passcode",
  ALARM: "alarm-clock",
  ALERT:"alert-circle",
  BELL:"bell-01",
  BANK:"bank",
  BACK: "chevron-left",
  CART: "shopping-cart-01",
  DELETE: "trash-03",
  EDIT: "edit-05",
  EXIT: "log-out-01",
  FILTER: "filter-funnel-01",
  GIFT: "gift-02",
  HEART: "heart",
  HOME: "home-03",
  CHECK:"check-circle",
  EYE:"eye",
  EYEOFF:"eye-off",
  GIFT:"gift-02",
  LINK:"link-01",
  LOCK:"lock-01",
  KEYBOARD:"keyboard-01",
  LOCKUNLOCK:"lock-unlocked-01",
  PAPERCLIP:"paperclip",
  HELP:"help-circle",
  HOURGLASS:"hourglass-03",
  BULB:'lightbulb-02',
  LINK:"link-01",
  INFO: "info-circle",
  MESSAGE: "message-chat-circle",
  MICROPHONE:"microphone-01",
  PAPERCLIP:"paperclip",
  NEXT: "chevron-right",
  PERSON: "user-circle",
  PROFILEEDIT:"user-edit",
  PHONE: "phone",
  CELLPHONE:"phone-01",
  SEARCH: "search-refraction",
  SEND: "send-03",
  SETTING: "settings-01",
  STAR: "star-01",
  WALLET:"wallet-02",
  SOUNDON:"volume-max",
  SOUNDOFF:"volume-x",
  CLOSE:"x-close",
  CLOSECIRCLE:"x-circle",
  ZOOMIN:"zoom-in",
  ZOOMOUT:"zoom-out",
  CALENDAR:"calendar-date",
  ZAP:"zap-fast",
  SHIELD:"shield-plus",
  SHARE:"share-07",
  SCAN:"scan",
  SALE:"sale-03",
  RECORDING:"recordomg-02",
  RECEIPT:"receipt-check",
  POWER:"power-02",
  PLUS:"plus-square",
  HELP:"help-circle",
  EYE:"eye",
  EYEOFF:"eye-off",
  RUPEE:"currency-rupee",
  MAIL:"mail-01"
  


  
  // STORE: "logo_store",
};