export const Roles = {
  CUSTOMER: "CUSTOMER",
  ADMIN: "ADMIN",
  SUPERADMIN: "SUPERADMIN",
};

export const OrderStatus = {
  PENDING: "PENDING",
  PROCESSING: "PROCESSING",
  SHIPPED: "SHIPPED",
  DELIVERED: "DELIVERED",
  CANCELLED: "CANCELLED",
};
